### ISSUE TITLE
problem with rotx, roty and rotz

### ISSUE THREAD

**Issue by VDB-Bram** [TuurvdHave/ViconSaving#1]
Depending on where you got the functions rotx, roty and rotz from the function might expect the input in radians or degrees. To not have this problem, it might be interesting to have the rotation matrix in full as input. See e.g. https://github.com/KULeuvenNeuromechanics/NeuromechanicsToolkit/blob/main/Dataprocessing/SelectRotationMatrix.m

**Comment by TuurvdHave** [comment]
https://github.com/TuurvdHave/ViconSaving/commit/fdade89aa5695ae7062f3fc8c42d3a1af1af07b8
